apiVersion: v1
kind: Service
metadata:
  name: indico-monitor
spec:
  selector:
    app: indico-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}
